version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      - ENVIRONMENT=production # Variável de ambiente para especificar o ambiente
